#!/usr/bin/env tsx
/**
 * rename-template.ts — turn this neutral starter template into a real project.
 *
 * The template ships with three brand-neutral placeholders:
 *   1. package scope         `@repo`                  (e.g. `@repo/db`, `@repo/web`)
 *   2. root workspace name   `internal-stack-template` (root package.json `name`)
 *   3. display-name default  "Internal Tools"          (NEXT_PUBLIC_APP_NAME default
 *                                                        in packages/env/src/client.ts)
 *
 * This script rewrites all three to a new project's identity in one pass.
 *
 * Usage:
 *   tsx scripts/rename-template.ts [@scope] [slug] ["App Name"]
 *   tsx scripts/rename-template.ts @acme acme-tools "Acme Tools" --yes
 *   tsx scripts/rename-template.ts --install      # also run `pnpm install` after
 *
 * Flags:
 *   --yes / -y    skip the confirmation prompt
 *   --install     run `pnpm install` automatically after rewriting
 *
 * Uses only Node built-ins (node:fs, node:path, node:readline,
 * node:child_process). Never touches pnpm-lock.yaml — `pnpm install`
 * regenerates it with the new scope.
 */

import { spawnSync } from "node:child_process";
import { type Dirent, existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import { createInterface } from "node:readline";

// ---------------------------------------------------------------------------
// Placeholders the template ships with.
// ---------------------------------------------------------------------------

const PLACEHOLDER_SCOPE = "@repo";
const PLACEHOLDER_SLUG = "internal-stack-template";
const PLACEHOLDER_APP_NAME = "Internal Tools";

// The env file whose NEXT_PUBLIC_APP_NAME default gets rewritten in-place.
const ENV_CLIENT_RELATIVE = join("packages", "env", "src", "client.ts");

// ---------------------------------------------------------------------------
// Walk configuration — what to include / exclude.
// ---------------------------------------------------------------------------

// Directory names skipped entirely, at any depth.
const IGNORED_DIRS: ReadonlySet<string> = new Set([
  "node_modules",
  ".git",
  ".next",
  ".turbo",
  "generated", // packages/db/generated — Prisma output, regenerated on build
  "dist",
]);

// Exact file names skipped (never rewritten — lockfile is regenerated by pnpm).
const IGNORED_FILES: ReadonlySet<string> = new Set(["pnpm-lock.yaml"]);

// Binary / non-text extensions we never read.
const BINARY_EXTENSIONS: ReadonlySet<string> = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".ico",
  ".pdf",
  ".woff",
  ".woff2",
  ".lock",
]);

// Text extensions we rewrite. SVGs and other non-listed assets are skipped.
const TEXT_EXTENSIONS: ReadonlySet<string> = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".json",
  ".jsonc",
  ".md",
  ".mdx",
  ".yml",
  ".yaml",
  ".css",
  ".prisma",
  ".sql",
  ".env",
  ".example",
  ".local",
]);

// Extension-less files that are still text and may carry placeholders.
const TEXT_FILENAMES: ReadonlySet<string> = new Set([
  ".env.example",
  "CODEOWNERS",
  "Dockerfile",
  ".npmrc",
  ".nvmrc",
]);

// This script lives in <repo>/scripts/. `process.argv[1]` is the absolute path
// tsx/node assigns to the entry script — module-format agnostic (works whether
// tsx emits CJS or ESM), unlike `import.meta.url`.
const SELF_PATH = resolve(process.argv[1] ?? __filenameFallback());
const REPO_ROOT = resolve(dirname(SELF_PATH), "..");

/** Last-resort path if argv[1] is somehow empty — assume cwd/scripts entry. */
function __filenameFallback(): string {
  return join(process.cwd(), "scripts", "rename-template.ts");
}

// ---------------------------------------------------------------------------
// Argument & input handling.
// ---------------------------------------------------------------------------

interface ParsedArgs {
  positionals: string[];
  yes: boolean;
  install: boolean;
}

function parseArgs(argv: string[]): ParsedArgs {
  const positionals: string[] = [];
  let yes = false;
  let install = false;
  for (const arg of argv) {
    if (arg === "--yes" || arg === "-y") {
      yes = true;
    } else if (arg === "--install") {
      install = true;
    } else if (arg.startsWith("-")) {
      console.warn(`Ignoring unknown flag: ${arg}`);
    } else {
      positionals.push(arg);
    }
  }
  return { positionals, yes, install };
}

interface Identity {
  scope: string; // without leading "@", lowercase — e.g. "acme"
  slug: string; // kebab-case — e.g. "acme-tools"
  appName: string; // human display name — e.g. "Acme Tools"
}

/** Normalize and validate an npm scope. Strips a leading "@", lowercases. */
function normalizeScope(input: string): string {
  const scope = input.trim().replace(/^@+/, "").toLowerCase();
  // npm scope rules: lowercase letters, digits, and the separators - _ .
  // Must start with an alphanumeric. No leading/trailing separators.
  if (!/^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$/.test(scope)) {
    throw new Error(
      `Invalid scope "${input}". A scope must be lowercase, start with a letter or ` +
        `digit, and contain only letters, digits, "-", "_" or "." (e.g. "@acme").`,
    );
  }
  return scope;
}

/** Validate a kebab-case package slug. */
function normalizeSlug(input: string): string {
  const slug = input.trim().toLowerCase();
  if (!/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(slug)) {
    throw new Error(
      `Invalid slug "${input}". Use kebab-case: lowercase letters, digits and ` +
        `hyphens, e.g. "acme-tools".`,
    );
  }
  return slug;
}

/** Validate a non-empty display name. */
function normalizeAppName(input: string): string {
  const appName = input.trim();
  if (appName.length === 0) {
    throw new Error('App name must not be empty (e.g. "Acme Tools").');
  }
  if (appName.includes('"')) {
    throw new Error("App name must not contain double quotes.");
  }
  return appName;
}

/**
 * Reads lines from stdin, robust to both interactive TTYs and piped input.
 *
 * `readline/promises`' sequential `question()` calls can hang after the first
 * answer when stdin is a closed pipe (all lines arrive, then EOF). This buffers
 * `line` events into a queue and tracks EOF, so each `question()` resolves
 * whether the input is typed live or piped all at once.
 */
class LineReader {
  readonly #rl = createInterface({ input: process.stdin });
  readonly #queued: string[] = [];
  #pending: ((line: string | null) => void) | null = null;
  #ended = false;

  constructor() {
    this.#rl.on("line", (line: string) => {
      if (this.#pending) {
        const resolve = this.#pending;
        this.#pending = null;
        resolve(line);
      } else {
        this.#queued.push(line);
      }
    });
    this.#rl.on("close", () => {
      this.#ended = true;
      if (this.#pending) {
        const resolve = this.#pending;
        this.#pending = null;
        resolve(null);
      }
    });
  }

  /** Print `question`, then resolve with the next line, or null at EOF. */
  question(question: string): Promise<string | null> {
    process.stdout.write(question);
    const next = this.#queued.shift();
    if (next !== undefined) {
      return Promise.resolve(next);
    }
    if (this.#ended) {
      return Promise.resolve(null);
    }
    return new Promise((resolve) => {
      this.#pending = resolve;
    });
  }

  close(): void {
    this.#rl.close();
  }
}

/**
 * Read one validated line. Loops until the input passes `validate`. Throws if
 * stdin ends before a valid answer is given (e.g. piped input ran out).
 */
async function prompt(
  reader: LineReader,
  question: string,
  validate: (value: string) => string,
): Promise<string> {
  while (true) {
    const answer = await reader.question(question);
    if (answer === null) {
      throw new Error(`No input received for: ${question.trim()}`);
    }
    try {
      return validate(answer);
    } catch (error) {
      console.error(`  ${(error as Error).message}`);
    }
  }
}

async function resolveIdentity(args: ParsedArgs, reader: LineReader | null): Promise<Identity> {
  const [scopeArg, slugArg, appNameArg] = args.positionals;

  // A reader is guaranteed present whenever an arg is missing (see main()).
  const ask = (question: string, validate: (value: string) => string): Promise<string> => {
    if (reader === null) {
      throw new Error("Internal error: missing input reader for an interactive prompt.");
    }
    return prompt(reader, question, validate);
  };

  const scope =
    scopeArg !== undefined
      ? normalizeScope(scopeArg)
      : await ask("Package scope (e.g. @acme): ", normalizeScope);

  const slug =
    slugArg !== undefined
      ? normalizeSlug(slugArg)
      : await ask("Workspace slug / root name (e.g. acme-tools): ", normalizeSlug);

  const appName =
    appNameArg !== undefined
      ? normalizeAppName(appNameArg)
      : await ask("Display name (e.g. Acme Tools): ", normalizeAppName);

  return { scope, slug, appName };
}

async function confirm(reader: LineReader, question: string): Promise<boolean> {
  const answer = await reader.question(question);
  const normalized = (answer ?? "").trim().toLowerCase();
  return normalized === "y" || normalized === "yes";
}

// ---------------------------------------------------------------------------
// File walking.
// ---------------------------------------------------------------------------

function isTextFile(filePath: string): boolean {
  const name = filePath.slice(filePath.lastIndexOf("/") + 1);
  if (TEXT_FILENAMES.has(name)) {
    return true;
  }
  const ext = extname(filePath).toLowerCase();
  if (ext === "") {
    return false; // unknown extension-less file — leave it alone
  }
  if (BINARY_EXTENSIONS.has(ext)) {
    return false;
  }
  return TEXT_EXTENSIONS.has(ext);
}

/** Recursively collect candidate text files under `dir`. */
function collectFiles(dir: string, out: string[]): void {
  let entries: Dirent[];
  try {
    entries = readdirSync(dir, { withFileTypes: true, encoding: "utf8" });
  } catch {
    return;
  }
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (IGNORED_DIRS.has(entry.name)) {
        continue;
      }
      collectFiles(fullPath, out);
      continue;
    }
    if (!entry.isFile()) {
      continue;
    }
    if (entry.name.endsWith(".tsbuildinfo")) {
      continue;
    }
    if (IGNORED_FILES.has(entry.name)) {
      continue;
    }
    if (fullPath === SELF_PATH) {
      continue; // never rewrite this script itself
    }
    if (!isTextFile(fullPath)) {
      continue;
    }
    out.push(fullPath);
  }
}

// ---------------------------------------------------------------------------
// Rewriting.
// ---------------------------------------------------------------------------

interface FileChange {
  path: string;
  scopeHits: number;
  slugHits: number;
  appNameHits: number;
}

function countOccurrences(haystack: string, needle: string): number {
  if (needle.length === 0) {
    return 0;
  }
  let count = 0;
  let index = haystack.indexOf(needle);
  while (index !== -1) {
    count += 1;
    index = haystack.indexOf(needle, index + needle.length);
  }
  return count;
}

/**
 * Apply the three replacements to a file's content. Returns the new content
 * and per-rule hit counts. The env-client app-name default is only touched in
 * the canonical client.ts to avoid clobbering unrelated strings.
 */
function rewriteContent(
  filePath: string,
  content: string,
  identity: Identity,
): { next: string; change: FileChange } {
  const scopeReplacement = `@${identity.scope}/`;
  const scopeNeedle = `${PLACEHOLDER_SCOPE}/`; // "@repo/" — anchored to the trailing slash

  const scopeHits = countOccurrences(content, scopeNeedle);
  const slugHits = countOccurrences(content, PLACEHOLDER_SLUG);

  let next = content;
  // Order matters: scope first, then slug. They don't overlap, but we keep the
  // documented order for predictability.
  if (scopeHits > 0) {
    next = next.split(scopeNeedle).join(scopeReplacement);
  }
  if (slugHits > 0) {
    next = next.split(PLACEHOLDER_SLUG).join(identity.slug);
  }

  // Targeted env-client default rewrite — only in packages/env/src/client.ts.
  let appNameHits = 0;
  if (relative(REPO_ROOT, filePath) === ENV_CLIENT_RELATIVE) {
    const defaultNeedle = `.default("${PLACEHOLDER_APP_NAME}")`;
    appNameHits = countOccurrences(next, defaultNeedle);
    if (appNameHits > 0) {
      next = next.split(defaultNeedle).join(`.default("${identity.appName}")`);
    }
  }

  return { next, change: { path: filePath, scopeHits, slugHits, appNameHits } };
}

// ---------------------------------------------------------------------------
// Reporting helpers.
// ---------------------------------------------------------------------------

function printPlan(identity: Identity, root: string): void {
  console.log("");
  console.log("Planned rename:");
  console.log(`  scope     ${PLACEHOLDER_SCOPE}/...           ->  @${identity.scope}/...`);
  console.log(`  slug      ${PLACEHOLDER_SLUG}  ->  ${identity.slug}`);
  console.log(
    `  appName   "${PLACEHOLDER_APP_NAME}"            ->  "${identity.appName}"  ` +
      `(default in ${ENV_CLIENT_RELATIVE})`,
  );
  console.log(`  root      ${root}`);
  console.log("");
}

function printChecklist(identity: Identity, ranInstall: boolean): void {
  console.log("");
  console.log("=".repeat(68));
  console.log("POST-RENAME CHECKLIST");
  console.log("=".repeat(68));
  let step = 1;
  if (!ranInstall) {
    console.log(
      `  ${step++}. pnpm install` +
        `   # regenerates pnpm-lock.yaml with the @${identity.scope} scope`,
    );
    console.log("        (do NOT hand-edit the lockfile)");
  }
  console.log(`  ${step++}. Generate an auth secret and paste it into both app env files:`);
  console.log("        openssl rand -base64 32");
  console.log("        -> BETTER_AUTH_SECRET (same value in apps/web + apps/admin)");
  console.log(`  ${step++}. Set DATABASE_URL (required for admin + any DB read).`);
  console.log(
    `  ${step++}. (Optional) Set NEXT_PUBLIC_APP_NAME per env — the default is now ` +
      `baked to "${identity.appName}".`,
  );
  console.log(
    `  ${step++}. For prod cross-app SSO, configure the shared cookie domain ` +
      "(see docs/04-authentication.md).",
  );
  console.log(`  ${step++}. Bring up the database and run:`);
  console.log("        pnpm db:migrate:dev && pnpm db:seed && pnpm dev");
  console.log("=".repeat(68));
  console.log("");
}

// ---------------------------------------------------------------------------
// Main.
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  // --- Idempotency / already-renamed detection --------------------------------
  // Scan for any remaining "@repo/" before resolving identity so we can exit
  // cleanly if the template was already renamed.
  const files: string[] = [];
  collectFiles(REPO_ROOT, files);

  const scopeNeedle = `${PLACEHOLDER_SCOPE}/`;
  const filesWithScope = files.filter(
    (file) => countOccurrences(readFileSync(file, "utf8"), scopeNeedle) > 0,
  );
  const filesWithSlug = files.filter(
    (file) => countOccurrences(readFileSync(file, "utf8"), PLACEHOLDER_SLUG) > 0,
  );

  if (filesWithScope.length === 0 && filesWithSlug.length === 0) {
    console.log(
      `No "${PLACEHOLDER_SCOPE}/" or "${PLACEHOLDER_SLUG}" placeholders found — ` +
        "this template looks already renamed. Nothing to do.",
    );
    process.exit(0);
  }

  // A single line reader for the whole interactive session. Created only when
  // some input is actually needed (missing args, or a confirmation is due), so
  // a fully arg-driven `--yes` run never blocks waiting on stdin.
  const needsInput = args.positionals.length < 3 || !args.yes;
  const reader = needsInput ? new LineReader() : null;

  let identity: Identity;
  let confirmed: boolean;
  try {
    // `reader` is non-null whenever an arg is missing; resolveIdentity only
    // prompts for missing args, so a null reader here is never read from.
    identity = await resolveIdentity(args, reader);

    // Guard: renaming to the same placeholder scope is a no-op.
    if (
      identity.scope === normalizeScope(PLACEHOLDER_SCOPE) &&
      identity.slug === PLACEHOLDER_SLUG
    ) {
      console.log("New identity equals the template placeholders — nothing to do.");
      process.exit(0);
    }

    printPlan(identity, REPO_ROOT);

    confirmed = args.yes
      ? true
      : await confirm(reader as LineReader, "Apply these changes? [y/N] ");
  } finally {
    reader?.close();
  }

  if (!confirmed) {
    console.log("Aborted. No files changed.");
    process.exit(0);
  }

  // --- Apply ------------------------------------------------------------------
  const changes: FileChange[] = [];
  let changedFileCount = 0;
  let totalScopeHits = 0;
  let totalSlugHits = 0;
  let totalAppNameHits = 0;

  for (const file of files) {
    const content = readFileSync(file, "utf8");
    const { next, change } = rewriteContent(file, content, identity);
    if (next !== content) {
      writeFileSync(file, next);
      changes.push(change);
      changedFileCount += 1;
      totalScopeHits += change.scopeHits;
      totalSlugHits += change.slugHits;
      totalAppNameHits += change.appNameHits;
    }
  }

  console.log("");
  if (changedFileCount === 0) {
    console.log("No files needed changes (already up to date).");
  } else {
    console.log(`Updated ${changedFileCount} file(s):`);
    for (const change of changes) {
      const parts: string[] = [];
      if (change.scopeHits > 0) parts.push(`${change.scopeHits} scope`);
      if (change.slugHits > 0) parts.push(`${change.slugHits} slug`);
      if (change.appNameHits > 0) parts.push(`${change.appNameHits} appName`);
      console.log(`  ${relative(REPO_ROOT, change.path)}  (${parts.join(", ")})`);
    }
    console.log("");
    console.log(
      `Totals: ${totalScopeHits} scope, ${totalSlugHits} slug, ` +
        `${totalAppNameHits} appName replacement(s).`,
    );
  }

  if (totalAppNameHits === 0 && existsSync(join(REPO_ROOT, ENV_CLIENT_RELATIVE))) {
    console.warn(
      `Warning: did not find .default("${PLACEHOLDER_APP_NAME}") in ` +
        `${ENV_CLIENT_RELATIVE}. Set NEXT_PUBLIC_APP_NAME manually if needed.`,
    );
  }

  // --- Optional install -------------------------------------------------------
  let ranInstall = false;
  if (args.install) {
    console.log("");
    console.log("Running `pnpm install` to regenerate the lockfile...");
    const result = spawnSync("pnpm", ["install"], {
      cwd: REPO_ROOT,
      stdio: "inherit",
    });
    if (result.status === 0) {
      ranInstall = true;
    } else {
      console.error("`pnpm install` failed or pnpm is not on PATH — run it yourself.");
    }
  }

  printChecklist(identity, ranInstall);
}

main().catch((error: unknown) => {
  console.error(`\nrename-template failed: ${(error as Error).message}`);
  process.exit(1);
});
